// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uksxrajzvitpxabuoyqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrc3hyYWp6dml0cHhhYnVveXFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5OTY2NjIsImV4cCI6MjA2MzU3MjY2Mn0.zWSp2qWmOPgLt2YJedNOI4XgtBss6kZZENYeA1Qwv9k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);